import { useMemo } from 'react';
import { AlertTriangle, ArrowRight, Check, ListChecks, Printer, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { Account, Transaction } from '../types';
import { createAutomaticPaymentPlans } from '../lib/scenarios/autoPlanner';

interface Props { isOpen: boolean; onClose: () => void; accounts: Account[]; transactions: Transaction[]; period: { start: string; end: string }; monthLabel: string; hideValues: boolean; }
const money = (value: number, hidden: boolean) => hidden ? '••••••' : value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default function AutomaticScenarioModal({ isOpen, onClose, accounts, transactions, period, monthLabel, hideValues }: Props) {
  const plans = useMemo(() => createAutomaticPaymentPlans(accounts, transactions, period), [accounts, transactions, period]);
  const expenses = useMemo(() => transactions.filter((t) => t.date >= period.start && t.date <= period.end && t.type === 'expense' && t.status !== 'completed' && t.kind !== 'card_purchase'), [transactions, period]);
  const transactionById = useMemo(() => new Map(expenses.map((item) => [item.id, item])), [expenses]);
  const accountById = useMemo(() => new Map(accounts.map((item) => [item.id, item])), [accounts]);
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-3 sm:p-6" role="dialog" aria-modal="true" aria-labelledby="automatic-scenario-title">
    <div id="automatic-scenario-print" className="automatic-scenario-print max-h-[94vh] w-full max-w-6xl overflow-y-auto rounded-2xl bg-[#0d0d12] shadow-2xl ring-1 ring-white/[0.1]">
      <header className="automatic-scenario-header sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-white/[0.08] bg-[#0d0d12] p-5 sm:p-6"><div><h2 id="automatic-scenario-title" className="text-xl font-bold text-white">Como distribuir os pagamentos de {monthLabel}</h2><p className="mt-1 max-w-3xl text-sm text-zinc-400">Cada caminho escolhe um banco para cada despesa e recalcula o saldo dessa conta a cada pagamento. Nada será alterado.</p></div><div className="automatic-scenario-actions flex shrink-0 gap-1"><button onClick={() => window.print()} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/[0.1] px-3 text-xs font-semibold text-zinc-200 hover:bg-white/[0.06]"><Printer size={15}/>Salvar PDF</button><button onClick={onClose} aria-label="Fechar simulação" className="min-h-11 min-w-11 rounded-xl text-zinc-400 hover:bg-white/[0.06] hover:text-white"><X className="mx-auto"/></button></div></header>
      {expenses.length === 0 ? <div className="p-12 text-center"><Check className="mx-auto mb-3 text-emerald-400"/><p className="font-semibold text-white">Não há despesas abertas neste mês.</p><p className="mt-1 text-sm text-zinc-400">Cadastre ou agende uma despesa para gerar os caminhos de pagamento.</p></div> : <div className="divide-y divide-white/[0.08]">{plans.map((plan, index) => {
        const Icon = plan.kind === 'protected' ? ShieldCheck : plan.kind === 'relief' ? ListChecks : Sparkles;
        const rentIsDeferred = plan.deferredTransactionIds.some((id) => { const item = transactionById.get(id); const text = `${item?.description || ''} ${item?.category || ''}`.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); return text.includes('aluguel'); });
        return <section key={plan.kind} className="p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start"><div className="lg:w-64 lg:shrink-0"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${plan.risk === 'high' ? 'bg-rose-500/10 text-rose-300' : plan.risk === 'medium' ? 'bg-amber-500/10 text-amber-300' : 'bg-emerald-500/10 text-emerald-300'}`}><Icon size={18}/></div><div><p className="text-xs text-zinc-500">Caminho {index + 1}</p><h3 className="text-sm font-bold text-white">{plan.title}</h3></div></div><p className="mt-3 text-xs leading-relaxed text-zinc-400">{plan.description}</p><dl className="mt-4 space-y-2 text-xs"><div className="flex justify-between gap-3 text-zinc-400"><dt>Total pago</dt><dd className="font-mono font-bold text-white">{money(plan.paidAmount, hideValues)}</dd></div><div className="flex justify-between gap-3 text-zinc-400"><dt>Adiado</dt><dd className="font-mono font-bold text-white">{money(plan.deferredAmount, hideValues)}</dd></div><div className="flex justify-between gap-3 text-zinc-400"><dt>Sobra fora da reserva</dt><dd className={`font-mono font-bold ${plan.projectedBalance < 0 ? 'text-rose-300' : 'text-emerald-300'}`}>{money(plan.projectedBalance, hideValues)}</dd></div></dl></div>
          <div className="min-w-0 flex-1"><div className="mb-3 grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-[#17171e] p-3 text-xs"><p className="text-zinc-500">Caixa disponível hoje</p><strong className="mt-1 block font-mono text-white">{money(plan.openingSpendableBalance, hideValues)}</strong></div><div className="rounded-xl bg-[#17171e] p-3 text-xs"><p className="text-zinc-500">Receitas ainda previstas</p><strong className="mt-1 block font-mono text-amber-300">+ {money(plan.expectedIncome, hideValues)}</strong></div><div className="rounded-xl bg-[#17171e] p-3 text-xs"><p className="text-zinc-500">Reserva separada</p><strong className="mt-1 block font-mono text-zinc-300">{money(plan.reserveBalance, hideValues)}</strong></div></div><ol className="space-y-2">{plan.allocations.map((allocation, itemIndex) => { const transaction = transactionById.get(allocation.transactionId); const account = accountById.get(allocation.accountId); if (!transaction || !account) return null; return <li key={transaction.id} className="grid gap-3 rounded-xl bg-[#17171e] p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white/[0.06] text-[10px] font-bold text-zinc-400">{itemIndex + 1}</span><p className="truncate text-sm font-semibold text-white">Pagar {transaction.description}</p><span className="shrink-0 font-mono text-xs text-zinc-300">{money(allocation.amount, hideValues)}</span></div><div className="mt-2 flex flex-wrap items-center gap-2 pl-8 text-xs"><span className="font-semibold" style={{ color: account.color }}>{account.name}</span><span className="text-zinc-500">disponível até o vencimento {money(allocation.balanceBefore, hideValues)}</span><ArrowRight size={13} className="text-zinc-600"/><span className={allocation.balanceAfter < 0 ? 'font-semibold text-rose-300' : 'font-semibold text-emerald-300'}>sobra {money(allocation.balanceAfter, hideValues)}</span></div></div><span className="hidden text-[10px] text-zinc-500 sm:block">vence {new Date(`${transaction.date}T12:00:00`).toLocaleDateString('pt-BR')}</span></li>; })}</ol>
          {plan.allocations.some((allocation) => allocation.transfers.length > 0) && <div className="mt-3 rounded-xl bg-blue-500/[0.07] p-3 text-xs text-blue-100"><strong>Transferências necessárias antes de pagar</strong><ul className="mt-2 space-y-2">{plan.allocations.flatMap((allocation) => allocation.transfers).map((transfer, transferIndex) => <li key={`${transfer.fromAccountId}-${transfer.toAccountId}-${transferIndex}`} className="flex flex-wrap items-center gap-2 rounded-lg bg-black/10 p-2"><span>Transferir <b>{money(transfer.amount, hideValues)}</b></span><span>de <b>{accountById.get(transfer.fromAccountId)?.name}</b></span><ArrowRight size={13}/><span><b>{accountById.get(transfer.toAccountId)?.name}</b></span><span className="text-blue-100/60">· sobra na origem {money(transfer.fromBalanceAfter, hideValues)}</span></li>)}</ul></div>}
          {plan.deferredTransactionIds.length > 0 && <div className="mt-3 rounded-xl bg-amber-500/[0.07] p-3 text-xs text-amber-100"><div className="flex items-center gap-2 font-semibold"><AlertTriangle size={14}/>Contas que ainda faltarão pagar</div><ul className="mt-3 space-y-2">{plan.deferredTransactionIds.map((id) => { const item = transactionById.get(id); if (!item) return null; const text = `${item.description} ${item.category}`.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); const isRent = text.includes('aluguel'); const originalAccount = accountById.get(item.accountId); return <li key={id} className="rounded-lg bg-black/10 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-amber-50">{item.description}</strong><span className="font-mono font-bold">{money(item.amount, hideValues)}</span></div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-amber-100/65"><span>Vence {new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')}</span><span>{item.category}</span>{originalAccount && <span>Conta original: {originalAccount.name}</span>}</div><p className="mt-2 text-[11px] text-amber-100/80"><strong>Motivo:</strong> {isRent ? 'as contas correntes somadas não cobrem o aluguel sem saldo negativo' : rentIsDeferred ? 'aguarda saldo suficiente para pagar o aluguel primeiro' : 'não há cobertura integral disponível sem deixar um banco negativo'}</p></li>; })}</ul></div>}</div></div></section>;
      })}</div>}
      <footer className="border-t border-white/[0.08] p-5 text-xs leading-relaxed text-zinc-500 sm:px-6">O aluguel é sempre o primeiro compromisso. Depois vêm contas prioritárias, atrasadas, fixas e essenciais. {plans[0]?.expectedIncomeIncluded ? 'Como este é um mês futuro, as receitas previstas do período entram na projeção e permanecem identificadas como valores ainda não recebidos.' : 'No mês atual, receitas ainda não recebidas aparecem separadamente e não são tratadas como caixa disponível.'} Reservas não entram na sobra disponível.</footer>
    </div>
  </div>;
}
