import { FormEvent, useMemo, useState } from 'react';
import { useFinanceStore } from '../store';
import { Check, ChevronDown, ChevronUp, Copy, Plus, ShoppingBag, ShoppingCart, Trash2, X } from 'lucide-react';

type ListMeta = { id: string; name: string; recurring: boolean };
const META_KEY = 'finance-shopping-lists-v1';
const loadLists = (): ListMeta[] => { try { const saved = JSON.parse(localStorage.getItem(META_KEY) || '[]'); return saved.length ? saved : [{ id: 'default', name: 'Compras do mês', recurring: true }]; } catch { return [{ id: 'default', name: 'Compras do mês', recurring: true }]; } };
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default function MarketListView() {
  const { marketItems, accounts, addMarketItem, toggleMarketItemInCart, deleteMarketItem, updateMarketItem, convertMarketListToExpense } = useFinanceStore();
  const [lists, setLists] = useState<ListMeta[]>(loadLists);
  const [activeId, setActiveId] = useState(lists[0].id);
  const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [quantity, setQuantity] = useState(1); const [category, setCategory] = useState('Outros'); const [store, setStore] = useState('');
  const [checkout, setCheckout] = useState(false); const [destination, setDestination] = useState(accounts[0]?.id || '');
  const items = useMemo(() => marketItems.filter((i) => (i.listId || 'default') === activeId), [marketItems, activeId]);
  const checked = items.filter((i) => i.inCart); const total = checked.reduce((s, i) => s + i.quantity * i.estimatedPrice, 0);
  const selectedAccount = accounts.find((a) => a.id === destination); const safeAfter = selectedAccount && selectedAccount.type !== 'credit' ? selectedAccount.balance - total : null;
  const saveLists = (next: ListMeta[]) => { setLists(next); localStorage.setItem(META_KEY, JSON.stringify(next)); };
  const createList = () => { const listName = prompt('Nome da nova lista:')?.trim(); if (!listName) return; const next = { id: `list-${Date.now()}`, name: listName, recurring: false }; saveLists([...lists, next]); setActiveId(next.id); };
  const duplicate = () => { const source = lists.find((l) => l.id === activeId); if (!source) return; const next = { id: `list-${Date.now()}`, name: `${source.name} — cópia`, recurring: source.recurring }; saveLists([...lists, next]); items.forEach((i, index) => addMarketItem(i.name, i.estimatedPrice, i.quantity, { listId: next.id, category: i.category, store: i.store, order: index, lastPurchasedPrice: i.estimatedPrice })); setActiveId(next.id); };
  const removeList = () => { if (lists.length === 1 || !confirm('Excluir esta lista e seus itens?')) return; items.forEach((i) => deleteMarketItem(i.id)); const next = lists.filter((l) => l.id !== activeId); saveLists(next); setActiveId(next[0].id); };
  const submit = (e: FormEvent) => { e.preventDefault(); if (!name.trim()) return; addMarketItem(name.trim(), Number(price.replace(',', '.')) || 0, quantity, { listId: activeId, category, store, order: items.length }); setName(''); setPrice(''); setQuantity(1); };
  const move = (index: number, delta: number) => { const other = items[index + delta]; if (!other) return; const copy = [...marketItems]; const a = copy.findIndex((i) => i.id === items[index].id); const b = copy.findIndex((i) => i.id === other.id); [copy[a], copy[b]] = [copy[b], copy[a]]; useFinanceStore.setState({ marketItems: copy }); };

  return <div className="mx-auto max-w-4xl space-y-5 pb-24">
    <div className="flex flex-wrap gap-2 rounded-2xl border border-white/[0.08] bg-[#0f0f13] p-3">
      <select aria-label="Lista ativa" value={activeId} onChange={(e) => setActiveId(e.target.value)} className="min-h-11 flex-1 rounded-xl bg-[#191920] px-3 text-sm text-white">{lists.map((l) => <option key={l.id} value={l.id}>{l.name}{l.recurring ? ' · recorrente' : ''}</option>)}</select>
      <button onClick={createList} className="min-h-11 rounded-xl border border-white/[0.1] px-3 text-xs text-white"><Plus size={15} className="inline"/> Nova lista</button>
      <button onClick={duplicate} className="min-h-11 rounded-xl border border-white/[0.1] px-3 text-xs text-white"><Copy size={15} className="inline"/> Duplicar</button>
      <button aria-label="Excluir lista" onClick={removeList} className="min-h-11 min-w-11 rounded-xl text-zinc-400 hover:text-rose-400"><Trash2 size={16} className="mx-auto"/></button>
    </div>
    <form onSubmit={submit} className="grid gap-2 rounded-2xl border border-white/[0.08] bg-[#0f0f13] p-4 sm:grid-cols-6">
      <input aria-label="Produto" required value={name} onChange={(e) => setName(e.target.value)} placeholder="Produto" className="min-h-11 rounded-xl bg-[#191920] px-3 text-sm text-white sm:col-span-2"/>
      <input aria-label="Mercado" value={store} onChange={(e) => setStore(e.target.value)} placeholder="Mercado" className="min-h-11 rounded-xl bg-[#191920] px-3 text-sm text-white"/>
      <input aria-label="Categoria" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Categoria" className="min-h-11 rounded-xl bg-[#191920] px-3 text-sm text-white"/>
      <input aria-label="Preço unitário" inputMode="decimal" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="0,00" className="min-h-11 rounded-xl bg-[#191920] px-3 text-sm text-white"/>
      <button className="min-h-11 rounded-xl bg-emerald-500 px-3 text-xs font-bold text-zinc-950">Adicionar ×{quantity}</button>
    </form>
    {items.length === 0 ? <div className="rounded-2xl border border-dashed border-white/[0.1] py-14 text-center text-sm text-zinc-500"><ShoppingBag className="mx-auto mb-2"/>Esta lista está vazia.</div> : <div className="space-y-2">{items.map((item, index) => <article key={item.id} className={`flex items-center gap-3 rounded-2xl border p-3 ${item.inCart ? 'border-emerald-500/25 bg-emerald-500/[0.06]' : 'border-white/[0.08] bg-[#0f0f13]'}`}>
      <button aria-label={`${item.inCart ? 'Desmarcar' : 'Marcar'} ${item.name}`} onClick={() => toggleMarketItemInCart(item.id)} className={`min-h-11 min-w-11 rounded-xl border ${item.inCart ? 'border-emerald-500 bg-emerald-500 text-black' : 'border-white/[0.12] text-transparent'}`}><Check className="mx-auto" size={16}/></button>
      <div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold text-white">{item.name}</h3><p className="text-[11px] text-zinc-500">{item.store || 'Mercado não definido'} · {item.category || 'Outros'}{item.lastPurchasedPrice != null && <span> · última {money(item.lastPurchasedPrice)}</span>}</p></div>
      <input aria-label={`Quantidade de ${item.name}`} type="number" min="1" value={item.quantity} onChange={(e) => updateMarketItem(item.id, Math.max(1, Number(e.target.value)), item.estimatedPrice)} className="h-11 w-14 rounded-lg bg-[#191920] px-2 text-center text-xs text-white"/>
      <input aria-label={`Preço de ${item.name}`} type="number" min="0" step="0.01" value={item.estimatedPrice} onChange={(e) => updateMarketItem(item.id, item.quantity, Number(e.target.value))} className="h-11 w-24 rounded-lg bg-[#191920] px-2 text-xs text-white"/>
      <div className="flex"><button disabled={index===0} aria-label="Mover para cima" onClick={() => move(index,-1)} className="min-h-11 min-w-8 disabled:opacity-20"><ChevronUp size={14}/></button><button disabled={index===items.length-1} aria-label="Mover para baixo" onClick={() => move(index,1)} className="min-h-11 min-w-8 disabled:opacity-20"><ChevronDown size={14}/></button></div>
      <button aria-label={`Excluir ${item.name}`} onClick={() => deleteMarketItem(item.id)} className="min-h-11 min-w-11 text-zinc-500 hover:text-rose-400"><Trash2 size={15} className="mx-auto"/></button>
    </article>)}</div>}
    <div className="flex flex-wrap gap-2"><button disabled={!checked.length} onClick={() => setCheckout(true)} className="min-h-12 flex-1 rounded-2xl bg-emerald-500 px-4 text-sm font-bold text-zinc-950 disabled:cursor-not-allowed disabled:opacity-40"><ShoppingCart size={16} className="mr-2 inline"/>Revisar {checked.length} {checked.length === 1 ? 'item' : 'itens'} — {money(total)}</button><button disabled={!checked.length} onClick={() => checked.forEach((i) => deleteMarketItem(i.id))} className="min-h-12 rounded-2xl border border-white/[0.1] px-4 text-xs text-zinc-300 disabled:opacity-40">Limpar comprados</button></div>
    {checkout && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><div className="w-full max-w-lg space-y-4 rounded-3xl border border-white/[0.1] bg-[#101015] p-5"><div className="flex items-center justify-between"><h2 id="checkout-title" className="font-bold text-white">Revisar lançamento</h2><button aria-label="Fechar" onClick={() => setCheckout(false)} className="min-h-11 min-w-11"><X className="mx-auto"/></button></div><ul className="max-h-48 space-y-2 overflow-auto">{checked.map((i) => <li key={i.id} className="flex justify-between text-xs text-zinc-300"><span>{i.quantity}× {i.name}</span><strong>{money(i.quantity*i.estimatedPrice)}</strong></li>)}</ul><div className="border-t border-white/[0.08] pt-3 text-right font-mono font-bold text-white">Total {money(total)}</div><label className="block text-xs text-zinc-400">Conta ou cartão<select autoFocus value={destination} onChange={(e) => setDestination(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl bg-[#191920] px-3 text-white">{accounts.map((a) => <option key={a.id} value={a.id}>{a.name} · {a.type === 'credit' ? 'cartão' : money(a.balance)}</option>)}</select></label>{safeAfter !== null && <p className={`rounded-xl p-3 text-xs ${safeAfter < 0 ? 'bg-rose-500/10 text-rose-300' : 'bg-emerald-500/10 text-emerald-300'}`}>Saldo após a compra: <strong>{money(safeAfter)}</strong>{safeAfter < 0 && ' · saldo negativo'}</p>}<button disabled={!destination} onClick={() => { convertMarketListToExpense(destination, activeId); setCheckout(false); }} className="min-h-12 w-full rounded-xl bg-emerald-500 font-bold text-zinc-950">Confirmar {checked.length} itens — {money(total)}</button></div></div>}
  </div>;
}
